"""refactor

Revision ID: 068042b3481a
Revises: 8bda8758ded9
Create Date: 2025-02-08 21:21:07.605862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068042b3481a'
down_revision: Union[str, None] = '8bda8758ded9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_participants_user_id_fkey', 'chat_participants', type_='foreignkey')
    op.create_foreign_key(None, 'chat_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'chat_participants', type_='foreignkey')
    op.create_foreign_key('chat_participants_user_id_fkey', 'chat_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
