"""create relationship between user, chat and message tables

Revision ID: 15d9aa140343
Revises: bd04e7d9aaba
Create Date: 2025-02-06 21:56:49.450442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d9aa140343'
down_revision: Union[str, None] = 'bd04e7d9aaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('chat_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
