"""create chat table

Revision ID: 6914a2053171
Revises: d56f87dde8bb
Create Date: 2025-02-06 20:42:12.869224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6914a2053171'
down_revision: Union[str, None] = 'd56f87dde8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('chat_type', sa.Enum('DIRECT', 'GROUP',
                              name='chattype'), nullable=False),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    # ### end Alembic commands ###
