"""add created_at and updated_at columns

Revision ID: 6b90411d10e9
Revises: 068042b3481a
Create Date: 2025-02-26 21:23:10.824535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b90411d10e9'
down_revision: Union[str, None] = '068042b3481a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('chats', 'chat_type',
               existing_type=postgresql.ENUM('DIRECT', 'GROUP', name='chatype'),
               type_=sa.Enum('DIRECT', 'GROUP', name='chattype'),
               existing_nullable=False)
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'created_at')
    op.alter_column('chats', 'chat_type',
               existing_type=sa.Enum('DIRECT', 'GROUP', name='chattype'),
               type_=postgresql.ENUM('DIRECT', 'GROUP', name='chatype'),
               existing_nullable=False)
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'created_at')
    # ### end Alembic commands ###
