"""create message table

Revision ID: 998ea65fa230
Revises: 6914a2053171
Create Date: 2025-02-06 21:01:35.730247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998ea65fa230'
down_revision: Union[str, None] = '6914a2053171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'FILE', name='messagetype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
